/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-dim": "#4ca0ff",
        secondary: "#c392fc",
        "inverse-primary": "#0060ac",
        "error-container": "#9f0519",
        "on-tertiary-container": "#003547",
        "tertiary-container": "#0ebef5",
        "on-secondary-fixed-variant": "#67389c",
        surface: "#090f15",
        "error-dim": "#d7383b",
        "primary-fixed-dim": "#3e96f4",
        "on-tertiary-fixed-variant": "#003f53",
        "tertiary-fixed": "#0ebef5",
        primary: "#73b1ff",
        "on-secondary-container": "#e1c5ff",
        "secondary-fixed": "#e2c7ff",
        "on-secondary-fixed": "#49167d",
        "surface-variant": "#1e272f",
        "secondary-dim": "#b888f1",
        "on-background": "#e6ebf4",
        "on-surface-variant": "#a6abb4",
        "tertiary-fixed-dim": "#00b0e3",
        "surface-dim": "#090f15",
        "on-primary-fixed-variant": "#002d55",
        "on-primary": "#002f59",
        tertiary: "#47ccff",
        "surface-container-highest": "#1e272f",
        background: "#090f15",
        outline: "#70767e",
        "on-tertiary": "#004055",
        "inverse-surface": "#f7f9ff",
        "secondary-container": "#5c2d91",
        "on-secondary": "#3e0373",
        "on-error-container": "#ffa8a3",
        "primary-fixed": "#53a3ff",
        "surface-container-low": "#0d141b",
        "primary-container": "#53a3ff",
        "surface-tint": "#73b1ff",
        "on-tertiary-fixed": "#001b25",
        "surface-container": "#131a22",
        error: "#ff716c",
        "surface-container-lowest": "#000000",
        "on-error": "#490006",
        "outline-variant": "#424850",
        "on-surface": "#e6ebf4",
        "tertiary-dim": "#00b0e3",
        "surface-container-high": "#182028",
        "surface-bright": "#242d37",
        "on-primary-fixed": "#000000",
        "secondary-fixed-dim": "#d8b5ff",
        "inverse-on-surface": "#50565d",
        "on-primary-container": "#002345",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
